// ============================================
// DATOS INICIALES - 10 EMPLEADOS DE EJEMPLO
// ============================================

export const empleadosIniciales = [
  {
    id: 'emp-001',
    foto: '',
    nombre: 'Carlos Alberto Martínez López',
    identidad: '0801-1985-04521',
    fechaNacimiento: '1985-03-15',
    genero: 'M',
    estadoCivil: 'Casado',
    direccion: 'Col. Kennedy, Blvd. Morazán, Tegucigalpa',
    telefono: '9945-2301',
    email: 'carlos.martinez@empresa.com',
    contactoEmergencia: { nombre: 'María López de Martínez', telefono: '9934-5567', parentesco: 'Esposa' },
    cargo: 'Gerente General',
    departamento: 'Dirección',
    fechaIngreso: '2020-01-15',
    tipoContrato: 'Indefinido',
    salarioBase: 65000,
    moneda: 'HNL',
    frecuenciaPago: 'mensual',
    jornada: 'diurna',
    horasJornada: 8,
    estado: 'activo',
    recomendaciones: 'Líder nato con excelente capacidad de gestión. Ha incrementado la productividad un 35% desde su ingreso.',
    observaciones: 'Pendiente renovación de contrato en enero 2027.',
    deducciones: { prestamos: [], embargos: [], fondoPension: 0 }
  },
  {
    id: 'emp-002',
    foto: '',
    nombre: 'Ana Patricia Reyes Hernández',
    identidad: '0801-1990-08934',
    fechaNacimiento: '1990-07-22',
    genero: 'F',
    estadoCivil: 'Soltera',
    direccion: 'Res. Los Álamos, Casa 15, San Pedro Sula',
    telefono: '3312-8845',
    email: 'ana.reyes@empresa.com',
    contactoEmergencia: { nombre: 'Roberto Reyes', telefono: '3318-9923', parentesco: 'Padre' },
    cargo: 'Contadora General',
    departamento: 'Finanzas',
    fechaIngreso: '2021-03-01',
    tipoContrato: 'Indefinido',
    salarioBase: 38000,
    moneda: 'HNL',
    frecuenciaPago: 'mensual',
    jornada: 'diurna',
    horasJornada: 8,
    estado: 'activo',
    recomendaciones: 'Excelente dominio de normativa fiscal hondureña. Mantiene las declaraciones al día sin errores.',
    observaciones: 'Interesada en certificación internacional de contabilidad.',
    deducciones: { prestamos: [{ id: 'pr-001', descripcion: 'Préstamo personal', montoTotal: 15000, cuotaMensual: 1500, saldoPendiente: 9000 }], embargos: [], fondoPension: 0 }
  },
  {
    id: 'emp-003',
    foto: '',
    nombre: 'José Manuel Flores Castillo',
    identidad: '0501-1988-12456',
    fechaNacimiento: '1988-11-05',
    genero: 'M',
    estadoCivil: 'Casado',
    direccion: 'Barrio El Centro, Comayagüela',
    telefono: '9876-5432',
    email: 'jose.flores@empresa.com',
    contactoEmergencia: { nombre: 'Sandra Castillo', telefono: '9867-3421', parentesco: 'Esposa' },
    cargo: 'Jefe de Ventas',
    departamento: 'Ventas',
    fechaIngreso: '2019-06-10',
    tipoContrato: 'Indefinido',
    salarioBase: 32000,
    moneda: 'HNL',
    frecuenciaPago: 'quincenal',
    jornada: 'diurna',
    horasJornada: 8,
    estado: 'activo',
    recomendaciones: 'Consistentemente supera las metas de ventas. Excelente relación con clientes corporativos.',
    observaciones: 'Se le asignó comisión del 3% sobre ventas totales a partir de enero 2026.',
    deducciones: { prestamos: [], embargos: [], fondoPension: 500 }
  },
  {
    id: 'emp-004',
    foto: '',
    nombre: 'Karla Daniela Mejía Rodríguez',
    identidad: '0801-1995-23456',
    fechaNacimiento: '1995-02-14',
    genero: 'F',
    estadoCivil: 'Soltera',
    direccion: 'Col. Lomas del Guijarro, Tegucigalpa',
    telefono: '8834-1122',
    email: 'karla.mejia@empresa.com',
    contactoEmergencia: { nombre: 'Patricia Rodríguez', telefono: '8823-4456', parentesco: 'Madre' },
    cargo: 'Diseñadora Gráfica',
    departamento: 'Marketing',
    fechaIngreso: '2023-02-20',
    tipoContrato: 'Indefinido',
    salarioBase: 22000,
    moneda: 'HNL',
    frecuenciaPago: 'mensual',
    jornada: 'diurna',
    horasJornada: 8,
    estado: 'activo',
    recomendaciones: 'Muy creativa y puntual. Ha mejorado significativamente la imagen corporativa.',
    observaciones: 'Completó curso de diseño UX/UI en marzo 2026.',
    deducciones: { prestamos: [], embargos: [], fondoPension: 0 }
  },
  {
    id: 'emp-005',
    foto: '',
    nombre: 'Roberto Alexander Pineda Sánchez',
    identidad: '0101-1992-34567',
    fechaNacimiento: '1992-09-30',
    genero: 'M',
    estadoCivil: 'Unión Libre',
    direccion: 'Col. Las Minitas, Bloque C, Tegucigalpa',
    telefono: '9712-3344',
    email: 'roberto.pineda@empresa.com',
    contactoEmergencia: { nombre: 'Lucía Sánchez', telefono: '9723-5566', parentesco: 'Madre' },
    cargo: 'Desarrollador de Software',
    departamento: 'Tecnología',
    fechaIngreso: '2022-08-01',
    tipoContrato: 'Indefinido',
    salarioBase: 45000,
    moneda: 'HNL',
    frecuenciaPago: 'mensual',
    jornada: 'diurna',
    horasJornada: 8,
    estado: 'activo',
    recomendaciones: 'Excelente desarrollador full-stack. Implementó el sistema ERP interno con éxito.',
    observaciones: 'Solicitud de aumento salarial pendiente de revisión.',
    deducciones: { prestamos: [{ id: 'pr-002', descripcion: 'Préstamo vivienda', montoTotal: 50000, cuotaMensual: 3000, saldoPendiente: 35000 }], embargos: [], fondoPension: 1000 }
  },
  {
    id: 'emp-006',
    foto: '',
    nombre: 'María Fernanda García Torres',
    identidad: '0801-1993-45678',
    fechaNacimiento: '1993-12-08',
    genero: 'F',
    estadoCivil: 'Casada',
    direccion: 'Res. Villa Real, Casa 42, San Pedro Sula',
    telefono: '3356-7788',
    email: 'maria.garcia@empresa.com',
    contactoEmergencia: { nombre: 'Fernando García', telefono: '3345-6677', parentesco: 'Esposo' },
    cargo: 'Coordinadora de RRHH',
    departamento: 'Recursos Humanos',
    fechaIngreso: '2021-11-15',
    tipoContrato: 'Indefinido',
    salarioBase: 28000,
    moneda: 'HNL',
    frecuenciaPago: 'mensual',
    jornada: 'diurna',
    horasJornada: 8,
    estado: 'activo',
    recomendaciones: 'Maneja excelentes relaciones interpersonales. Redujo la rotación de personal en un 20%.',
    observaciones: 'Certificada en gestión de talento humano.',
    deducciones: { prestamos: [], embargos: [], fondoPension: 0 }
  },
  {
    id: 'emp-007',
    foto: '',
    nombre: 'Luis Enrique Bonilla Ávila',
    identidad: '0301-1987-56789',
    fechaNacimiento: '1987-05-20',
    genero: 'M',
    estadoCivil: 'Casado',
    direccion: 'Barrio Cabañas, La Ceiba, Atlántida',
    telefono: '9567-8899',
    email: 'luis.bonilla@empresa.com',
    contactoEmergencia: { nombre: 'Carmen Ávila', telefono: '9556-7788', parentesco: 'Esposa' },
    cargo: 'Supervisor de Operaciones',
    departamento: 'Operaciones',
    fechaIngreso: '2018-04-02',
    tipoContrato: 'Indefinido',
    salarioBase: 25000,
    moneda: 'HNL',
    frecuenciaPago: 'quincenal',
    jornada: 'mixta',
    horasJornada: 7,
    estado: 'activo',
    recomendaciones: 'Gran compromiso y dedicación. Nunca ha faltado a su trabajo sin justificación.',
    observaciones: 'Tiene embargo judicial activo por pensión alimenticia.',
    deducciones: { prestamos: [], embargos: [{ id: 'emb-001', descripcion: 'Pensión alimenticia', porcentaje: 15, montoFijo: 0 }], fondoPension: 0 }
  },
  {
    id: 'emp-008',
    foto: '',
    nombre: 'Sofía Alejandra Ramos Zuniga',
    identidad: '0801-1998-67890',
    fechaNacimiento: '1998-08-12',
    genero: 'F',
    estadoCivil: 'Soltera',
    direccion: 'Col. Palmira, Edificio Morazán, Apt 5B, Tegucigalpa',
    telefono: '8823-4455',
    email: 'sofia.ramos@empresa.com',
    contactoEmergencia: { nombre: 'Alejandra Zuniga', telefono: '8812-3344', parentesco: 'Madre' },
    cargo: 'Asistente Administrativa',
    departamento: 'Administración',
    fechaIngreso: '2024-01-10',
    tipoContrato: 'Indefinido',
    salarioBase: 15000,
    moneda: 'HNL',
    frecuenciaPago: 'mensual',
    jornada: 'diurna',
    horasJornada: 8,
    estado: 'activo',
    recomendaciones: 'Muy organizada y proactiva. Aprendizaje rápido.',
    observaciones: 'En período de evaluación para aumento salarial.',
    deducciones: { prestamos: [], embargos: [], fondoPension: 0 }
  },
  {
    id: 'emp-009',
    foto: '',
    nombre: 'Diego Armando Velásquez Cruz',
    identidad: '0501-1991-78901',
    fechaNacimiento: '1991-04-25',
    genero: 'M',
    estadoCivil: 'Soltero',
    direccion: 'Col. Torocagua, Comayagüela',
    telefono: '9678-9900',
    email: 'diego.velasquez@empresa.com',
    contactoEmergencia: { nombre: 'Mario Velásquez', telefono: '9667-8899', parentesco: 'Padre' },
    cargo: 'Ejecutivo de Ventas',
    departamento: 'Ventas',
    fechaIngreso: '2023-07-01',
    tipoContrato: 'Indefinido',
    salarioBase: 18000,
    moneda: 'HNL',
    frecuenciaPago: 'quincenal',
    jornada: 'diurna',
    horasJornada: 8,
    estado: 'activo',
    recomendaciones: 'Buen desempeño en captación de nuevos clientes. Superó meta del Q1 2026.',
    observaciones: 'Comisión del 2% sobre ventas personales.',
    deducciones: { prestamos: [{ id: 'pr-003', descripcion: 'Préstamo emergencia', montoTotal: 8000, cuotaMensual: 800, saldoPendiente: 4800 }], embargos: [], fondoPension: 0 }
  },
  {
    id: 'emp-010',
    foto: '',
    nombre: 'Andrea Cristina Núñez Padilla',
    identidad: '0801-1994-89012',
    fechaNacimiento: '1994-06-18',
    genero: 'F',
    estadoCivil: 'Casada',
    direccion: 'Res. Santa Fe, Casa 8, Tegucigalpa',
    telefono: '8845-6677',
    email: 'andrea.nunez@empresa.com',
    contactoEmergencia: { nombre: 'Cristian Padilla', telefono: '8834-5566', parentesco: 'Esposo' },
    cargo: 'Analista de Logística',
    departamento: 'Operaciones',
    fechaIngreso: '2022-05-15',
    tipoContrato: 'Indefinido',
    salarioBase: 20000,
    moneda: 'HNL',
    frecuenciaPago: 'mensual',
    jornada: 'diurna',
    horasJornada: 8,
    estado: 'activo',
    recomendaciones: 'Excelente capacidad analítica. Optimizó rutas de distribución ahorrando 12% en costos.',
    observaciones: 'En proceso de maestría en Supply Chain Management.',
    deducciones: { prestamos: [], embargos: [], fondoPension: 300 }
  }
];

export const configuracionInicial = {
  empresa: {
    nombre: 'Empresa Elsa',
    rtn: '08011985045210',
    direccion: 'Col. Kennedy, Blvd. Morazán, Tegucigalpa, Francisco Morazán, Honduras',
    telefono: '2234-5678',
    email: 'info@empresaelsa.hn',
    logo: ''
  },
  techoIHSS: 11903.13,
  porcentajeIHSS_IVM: 2.5,
  porcentajeIHSS_EM: 2.5,
  porcentajeRAP: 1.5,
  tablaISR: [
    { desde: 0.01, hasta: 217493.16, tasa: 0 },
    { desde: 217493.17, hasta: 331638.50, tasa: 15 },
    { desde: 331638.51, hasta: 771252.38, tasa: 20 },
    { desde: 771252.39, hasta: Infinity, tasa: 25 }
  ],
  tiposCambio: {
    USD: 24.85,
    EUR: 27.50
  },
  feriados: [
    { fecha: '01-01', nombre: 'Año Nuevo' },
    { fecha: '04-10', nombre: 'Jueves Santo' },
    { fecha: '04-11', nombre: 'Viernes Santo' },
    { fecha: '04-12', nombre: 'Sábado de Gloria' },
    { fecha: '04-14', nombre: 'Día de las Américas' },
    { fecha: '05-01', nombre: 'Día del Trabajo' },
    { fecha: '09-15', nombre: 'Día de la Independencia' },
    { fecha: '10-03', nombre: 'Nacimiento de Francisco Morazán' },
    { fecha: '10-12', nombre: 'Día de la Raza' },
    { fecha: '10-21', nombre: 'Día de las Fuerzas Armadas' },
    { fecha: '12-25', nombre: 'Navidad' }
  ],
  vacaciones: [
    { anios: 1, dias: 10 },
    { anios: 2, dias: 12 },
    { anios: 3, dias: 15 },
    { anios: 4, dias: 20 }
  ],
  horasExtra: {
    diurna: 25,
    nocturna: 50,
    nocturna_prolongada: 75,
    feriado: 100
  }
};

export const credencialesAdmin = {
  usuario: 'admin',
  password: 'admin2026'
};
